namespace:
  name: ansible
cronJob:
  name: tg-infrastructure
  schedule: "0 * * * *"
  spec:
    image: tarabutgateway/infrastructure.ansible:develop
  oci:
    key:
      secretName: oci-creds
      secretKey: api-key
    config: |
      [DEFAULT]
      key_file=/root/.oci-key/oci_api_key.pem
  env: []
sshKeys:
  - secretName: ssh-key-secret
    secretKey: private-key
inventories: []
playbooks: {}
